### ISSUE TITLE
How can I easily disable for fzf or other non-source code splits?

### ISSUE THREAD

**Issue by AlanWarren** [tveskag/nvim-blame-line#10]
Hello,

Awesome plugin!  

I notice whenever I have `:TogggleBlameLine` on, and I switch buffers using fzf `:Buffer` I receive the following error. 

```
Error detected while processing function <lambda>258[1]..<SNR>141_handler[1]..<SNR>141_getAnnotation:
line    1:
E121: Undefined variable: b:BlameLineGitdir
Press ENTER or type command to continue
```
I tried to disable the blame line based on &buftype == 'terminal' but didn't have any luck.  
I'm using nvim v0.4.0-1597 on MacOS from inside iTerm2 / tmux. 

Any ideas?

**Comment by asgerviggo** [comment]
Hey, thanks! I really appreciate it.
These kinds of errors should be handled behind the scenes in the latest update.
