### ISSUE TITLE
Error: Function name cannot contain a colon: b:ToggleBlameLine()

### ISSUE THREAD

**Issue by benwoodward** [tveskag/nvim-blame-line#11]
![image](https://user-images.githubusercontent.com/1472981/71685496-96937780-2dec-11ea-8250-0dc14f4bea62.png)

Received this error on executing `:ToggleBlameLine`

**Comment by caenrique** [comment]
Me too

**Comment by asgerviggo** [comment]
Is this still an issue? I cannot reproduce it. If it is, please provide some steps to reproduce it and I'll have a look.
