### ISSUE TITLE
Not a git repository error when enabling the plugin

### ISSUE THREAD

**Issue by saaguero** [tveskag/nvim-blame-line#2]
Plugin seems to be failing (both in latest vim as well as neovim) whenever I `ToggleBlameLine` or `EnableBlameLine` with the error:

`fatal: not a git repository: '/' `

**Comment by asgerviggo** [comment]
Which operating system are you using? Does this happen in any document you open or just some? Are you using a gui?

**Comment by asgerviggo** [comment]
nvim-blame-line will now simply echo any errors git throws at it.
