### ISSUE TITLE
Is it possible to debounce?

### ISSUE THREAD

**Issue by simonsmith** [tveskag/nvim-blame-line#3]
If I hold `j` or `k` to scroll the editor then freezes whilst it catches up and eventually my cursor moves. I presume this might be because it tries to run the blame on every line? Is there a way to run it after user input has stopped for half a second or so?

**Comment by asgerviggo** [comment]
I've added debounce in the latest commit. It uses timers and lambda functions, so you need to have these installed, otherwise it will run without debouncing.

**Comment by simonsmith** [comment]
Works really well! Thank you 👍

**Comment by ghost** [comment]
Can you explains more on how to make the debounce works?
