### ISSUE TITLE
Prevent overriding existing virtual text

### ISSUE THREAD

**Issue by kristijanhusak** [tveskag/nvim-blame-line#4]
Hi,

is there a way to prevent overriding existing virtual text?

I'm using ALE and it's option to show errors in virtual text, and git blame overrides it. I would like it to be shown only when there's no any other virtualtext.

**Comment by asgerviggo** [comment]
I'm not sure there's a way to check where ale has set virtual text before blame line overrides it, 
but what you can do is set `let g:blameLineUseVirtualText = 0` in your vimrc, then it will write git blame as status messages instead.

**Comment by kristijanhusak** [comment]
Yeah that's true, i can't find any either. Thanks for help.
