### ISSUE TITLE
Not a valid object on ToggleBlameLine

### ISSUE THREAD

**Issue by mblarsen** [tveskag/nvim-blame-line#9]
This happens when invoking `ToggleBlameLine` 

```
fatal: Not a valid object name HEAD:/mnvolume_sgp1_01/workspace/XXX/XXX/plugin.php
```

However, if I first `EnableBlameLine` then I can toggle as much as I want to after that.

System:  
Ubuntu 18.4  
Neovim

**Comment by jlbribeiro** [comment]
I can report the same on Arch Linux using Neovim `v0.3.8`. To add a bit more context, I get the same message as @mblarsen:

```
fatal: Not a valid object name HEAD:/homusername/path/to/file.go
```

Notice how it deletes `e/` (i.e. it should be `/home/username/...`), similarly to how it deletes `t/` (supposedly it should be `/mnt/volume_sgp1_01/...`) in @mblarsen's path.

As @mblarsen's also reports, after calling `EnableBlameLine`, `ToggleBlameLine` behaves as expected.

Btw, thank you so much for this amazing plug-in!

**Comment by asgerviggo** [comment]
The way nvim-blame-line checks the current file path in git has been changed, I believe it should fix this issue. I'm closing this, but perhaps @jlbribeiro you could confirm this?
